spring.application.name=Medicine Reminder API
server.address=0.0.0.0
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/medrem}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.write-date-timestamps-as-nanoseconds=false
spring.jackson.date-format=com.fasterxml.jackson.databind.util.StdDateFormat
spring.jackson.time-zone=UTC

spring.flyway.enabled=false

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=86400000

telegram.bot.token=${TELEGRAM_BOT_TOKEN}

vapid.public.key=${VAPID_PUBLIC_KEY}
vapid.private.key=${VAPID_PRIVATE_KEY}
vapid.subject=${VAPID_SUBJECT:mailto:admin@pill-o.com}

logging.level.org.springframework.security=OFF
logging.level.com.op1m.medrem=INFO
logging.level.org.hibernate=WARN
logging.level.org.springframework=WARN

spring.cache.type=caffeine

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never